# Based on https://habrahabr.ru/post/329264/
# Additional GCC / clang versions:
#   - https://docs.travis-ci.com/user/languages/cpp/

dist: trusty
sudo: required

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - AVCPP=1
    matix:
        - BUILD_CONFIGURATION=Debug
        - BUILD_CONFIGURATION=Release

matrix:
    include:
        - compiler: gcc
          env: BUILD_CONFIGURATION=Debug   CC=gcc-7 CXX=g++-7

        - compiler: gcc
          env: BUILD_CONFIGURATION=Release   CC=gcc-7 CXX=g++-7

        - compiler: gcc
          env: BUILD_CONFIGURATION=Debug   CC=gcc-5 CXX=g++-5

        - compiler: gcc
          env: BUILD_CONFIGURATION=Release   CC=gcc-5 CXX=g++-5

    exclude:
        # exclude some elements from build matrix:
        - os:       osx
          compiler: gcc

        - compiler: gcc
          env: BUILD_CONFIGURATION=Debug

        - compiler: gcc
          env: BUILD_CONFIGURATION=Release

install:
    # setup env:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
    # build and test project:
    - mkdir build
    - cd build
    #- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - cmake --build .
    #- ctest --output-on-failure

#deploy:
#    # push tagged-commits to GitHub Releases:
#    provider:     releases
#    file:         <package-file>
#    skip_cleanup: true
#    overwrite:    true
#
#    api_key:
#        secure:   <encrypted-github-token>
#
#    on:
#        tags:     true

