name: Cross-platform build using conan

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '34 5 * * 5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CMake:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        ffmpeg: [ 8.0.1, 7.1.3, 6.1.1 ]

    steps:
      - uses: conan-io/setup-conan@v1
      - uses: actions/checkout@v6

      - name: Get conan home
        shell: bash
        id: conan_home
        run: echo path=`conan config home` >> $GITHUB_OUTPUT
      - name: Cache conan artifacts
        id: conan-artifacts
        uses: actions/cache@v5
        with:
          path: ${{ steps.conan_home.outputs.path }}
          key: conan-${{ matrix.platform }}-cmake
      - name: Restart from scratch every Friday
        run: rm -rf ${{ steps.conan_home.outputs.path }}
        shell: bash
        if: github.event_name == 'schedule'

      - run: conan profile detect --force
      - run: conan install --requires ffmpeg/${{ matrix.ffmpeg }} -b=missing -g CMakeToolchain -g CMakeDeps -of build -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=true

      - run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" ..
        working-directory: ${{ github.workspace }}/build

      - run: cmake --build
        working-directory: ${{ github.workspace }}/build

      - run: cmake --test
        working-directory: ${{ github.workspace }}/build
